name: Build and Deploy Docker to Azure WebApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: alexandre-cuneo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/myapp:${{ github.sha }} .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/myapp:${{ github.sha }}

    - name: Deploy to Azure WebApp using container
      run: |
        az webapp config container set \
          --name ${{ env.AZURE_WEBAPP_NAME }} \
          --resource-group <alexandre-cuneo_group> \
          --docker-custom-image-name ${{ secrets.ACR_LOGIN_SERVER }}/myapp:${{ github.sha }}

    - name: Restart Azure WebApp
      run: az webapp restart --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group <alexandre-cuneo_group>